In [1]:
#导入数据
import pandas as pd
df1 = pd.read_excel(r'D:\pythonProject\a.xlsx') 
df2 = pd.read_excel(r'D:\pythonProject\t.xlsx')
df3 = pd.read_excel(r'D:\pythonProject\k.xlsx')
df1.columns = ["Timestamp", "Accelaration-X", "Accelaration-Y", "Accelaration-Z"] 
df2.columns = ["Timestamp", "AngularVelocity-X", "AngularVelocity-Y", "AngularVelocity-Z"]
df3.columns = ["Timestamp","latitude", "longtitude", "altitude", "speed", "course", "hacc"]
#每秒钟取均值
from datetime  import datetime
result = pd.DataFrame()
df1['minute'] = df1['Timestamp'].apply(lambda x : datetime.strftime(x ,'%Y-%m-%d %H:%M:%S'))
data1 = df1.groupby('minute').mean().reset_index()
df2['minute'] = df2['Timestamp'].apply(lambda x : datetime.strftime(x ,'%Y-%m-%d %H:%M:%S'))
data2 = df1.groupby('minute').mean().reset_index()
df3['minute'] = df3['Timestamp'].apply(lambda x : datetime.strftime(x ,'%Y-%m-%d %H:%M:%S'))
data3 = df3.groupby('minute').mean().reset_index()
#三张表连一起
result =pd.merge(pd.merge(data1,data2,on = 'minute',how = 'inner'),data3,on='minute',how='left')
#打标签（伪数据，设定47分和47分在吸烟）
result['is_smoke'] = 0
result.loc[result.minute.apply(lambda x : (x[-5:-3] =='47')or  (x[-5:-3] =='49')),'is_smoke'] = 1
result.query('is_smoke == 1')
result

,minute,Accelaration-X_x,Accelaration-Y_x,Accelaration-Z_x,Accelaration-X_y,Accelaration-Y_y,Accelaration-Z_y,latitude,longtitude,altitude,speed,course,hacc,is_smoke
0,2023-04-09 17:45:51,-0.361969,1.922067,9.362174,-0.361969,1.922067,9.362174,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2023-04-09 17:45:52,-1.511003,2.582849,9.038385,-1.511003,2.582849,9.038385,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2023-04-09 17:45:53,-2.717943,1.958033,8.947224,-2.717943,1.958033,8.947224,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2023-04-09 17:45:54,-3.874633,2.415706,8.967896,-3.874633,2.415706,8.967896,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2023-04-09 17:45:55,-3.929179,1.575039,8.724689,-3.929179,1.575039,8.724689,31.02398,121.43157,8.768,0.0,0.0,35.000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,2023-04-09 17:50:27,-5.482664,2.067261,8.312259,-5.482664,2.067261,8.312259,NaN,NaN,NaN,NaN,NaN,NaN,0
277,2023-04-09 17:50:28,-4.378470,2.304757,8.533006,-4.378470,2.304757,8.533006,31.02407,121.43173,9.122,0.0,0.0,55.333,0
278,2023-04-09 17:50:29,-4.309673,2.124652,7.840920,-4.309673,2.124652,7.840920,31.02403,121.43155,9.015,0.0,0.0,35.000,0
279,2023-04-09 17:50:30,-4.220384,2.400962,8.568108,-4.220384,2.400962,8.568108,NaN,NaN,NaN,NaN,NaN,NaN,0
280,2023-04-09 17:50:31,-4.240831,3.370466,8.416211,-4.240831,3.370466,8.416211,NaN,NaN,NaN,NaN,NaN,NaN,0

In [3]:
result.info

<bound method DataFrame.info of                   minute  Accelaration-X_x  Accelaration-Y_x  \
0    2023-04-09 17:45:51         -0.361969          1.922067
1    2023-04-09 17:45:52         -1.511003          2.582849
2    2023-04-09 17:45:53         -2.717943          1.958033
3    2023-04-09 17:45:54         -3.874633          2.415706
4    2023-04-09 17:45:55         -3.929179          1.575039
..                   ...               ...               ...
276  2023-04-09 17:50:27         -5.482664          2.067261
277  2023-04-09 17:50:28         -4.378470          2.304757
278  2023-04-09 17:50:29         -4.309673          2.124652
279  2023-04-09 17:50:30         -4.220384          2.400962
280  2023-04-09 17:50:31         -4.240831          3.370466

     Accelaration-Z_x  Accelaration-X_y  Accelaration-Y_y  Accelaration-Z_y  \
0            9.362174         -0.361969          1.922067          9.362174
1            9.038385         -1.511003          2.582849          9.038385
2            8.947224         -2.717943          1.958033          8.947224
3            8.967896         -3.874633          2.415706          8.967896
4            8.724689         -3.929179          1.575039          8.724689
..                ...               ...               ...               ...
276          8.312259         -5.482664          2.067261          8.312259
277          8.533006         -4.378470          2.304757          8.533006
278          7.840920         -4.309673          2.124652          7.840920
279          8.568108         -4.220384          2.400962          8.568108
280          8.416211         -4.240831          3.370466          8.416211

     latitude  longtitude  altitude  speed  course    hacc  is_smoke
0         NaN         NaN       NaN    NaN     NaN     NaN         0
1         NaN         NaN       NaN    NaN     NaN     NaN         0
2         NaN         NaN       NaN    NaN     NaN     NaN         0
3         NaN         NaN       NaN    NaN     NaN     NaN         0
4    31.02398   121.43157     8.768    0.0     0.0  35.000         0
..        ...         ...       ...    ...     ...     ...       ...
276       NaN         NaN       NaN    NaN     NaN     NaN         0
277  31.02407   121.43173     9.122    0.0     0.0  55.333         0
278  31.02403   121.43155     9.015    0.0     0.0  35.000         0
279       NaN         NaN       NaN    NaN     NaN     NaN         0
280       NaN         NaN       NaN    NaN     NaN     NaN         0

[281 rows x 14 columns]>

In [4]:
result.describe()

,Accelaration-X_x,Accelaration-Y_x,Accelaration-Z_x,Accelaration-X_y,Accelaration-Y_y,Accelaration-Z_y,latitude,longtitude,altitude,speed,course,hacc,is_smoke
count,281.000000,281.000000,281.000000,281.000000,281.000000,281.000000,64.000000,64.000000,64.000000,64.0,64.0,64.000000,281.000000
mean,-5.962549,0.398886,6.939324,-5.962549,0.398886,6.939324,31.024032,121.431678,9.068531,0.0,0.0,43.074984,0.427046
std,2.097930,1.847216,1.925704,2.097930,1.847216,1.925704,0.000025,0.000046,0.104896,0.0,0.0,8.660416,0.495532
min,-9.170230,-3.287883,3.433725,-9.170230,-3.287883,3.433725,31.023970,121.431550,8.768000,0.0,0.0,35.000000,0.000000
25%,-8.178318,-1.153097,4.695945,-8.178318,-1.153097,4.695945,31.024010,121.431650,9.053000,0.0,0.0,35.000000,0.000000
50%,-5.482664,0.988410,7.622344,-5.482664,0.988410,7.622344,31.024030,121.431690,9.093500,0.0,0.0,41.414750,0.000000
75%,-4.193020,1.958033,8.671318,-4.193020,1.958033,8.671318,31.024050,121.431710,9.151500,0.0,0.0,52.255000,1.000000
max,-0.361969,3.370466,9.494456,-0.361969,3.370466,9.494456,31.024070,121.431750,9.189000,0.0,0.0,55.333000,1.000000

ValueError: could not convert string to float: '2023-04-09 17:45:51'